---
abstract: 'Authenticate with Twitter'
author:
  - 'Alexis Sukrieh <sukria@sukria.net>'
  - 'Dancer Core Developers'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Auth-Twitter
provides:
  Dancer::Plugin::Auth::Twitter:
    file: lib/Dancer/Plugin/Auth/Twitter.pm
    version: 0.03
requires:
  Carp: 0
  Dancer: 0
  Dancer::Plugin: 0
  Net::Twitter: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/PerlDancer/Dancer-Plugin-Auth-Twitter
  repository: https://github.com/PerlDancer/Dancer-Plugin-Auth-Twitter
version: 0.03
